# ç½‘ç«™ä¿¡æ¯
site_name: ColossalAI æ–‡æ¡£ ğŸ•®  #
site_url: https://eanyang7.github.io/ColossalAI_docs # mkdocs serve â€”â€”ã€‹ Browser connected: http://127.0.0.1:8000/xxx/
site_description: "ColossalAI_docs" #
site_author: Ean Yang
# ä»“åº“
repo_url: https://github.com/EanYang7/ColossalAI_docs #
repo_name: githubä»“åº“

theme:
  name: material
  language: zh
  # ç½‘ç«™logo
  logo: assets/logo.jpg #
  # ç½‘ç«™favicon
  favicon: assets/favicon.jpg #
  # è®¾ç½®å³ä¸Šè§’å›¾æ ‡
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
  palette:
    # å¯é€‰é¢œè‰²è§https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    # åˆ‡æ¢ä¸ºæš—é»‘æ¨¡å¼
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red # ä¸»è‰²è°ƒ
      accent: deep purple # å¼ºè°ƒè‰²è°ƒ
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢ä¸ºæš—é»‘æ¨¡å¼

    # åˆ‡æ¢ä¸ºæµ…è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: red
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢ä¸ºæµ…è‰²æ¨¡å¼
  # å¯¼èˆªè®¾ç½®
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs #é€‰é¡¹å¡
    # - navigation.tabs.sticky #é€‰é¡¹å¡å›ºå®šï¼Œæ»šåŠ¨æ—¶è¿˜å¯è§
    # - navigation.sections #ç« èŠ‚è§†å›¾ï¼Œå¯ä»¥å’Œtabsæ­é…ä½¿ç”¨
    # - navigation.expand #å±•å¼€ä¾§è¾¹æ 
    - navigation.prune
    # - navigation.indexes # ç‚¹å‡»æ–‡ä»¶å¤¹æ˜¾ç¤ºindex.mdçš„å†…å®¹
    - navigation.top # å›åˆ°é¡¶éƒ¨
    - toc.follow # ç›®å½•è·Ÿéš
    - header.autohide # æ»šåŠ¨æ—¶éšè—é¡¶éƒ¨
    - navigation.footer # åº•éƒ¨å¯¼èˆªï¼Œä¸Šä¸‹é¡µ
    - search.suggest # æœç´¢å»ºè®®
    - search.highlight # æœç´¢é«˜äº®
    - search.share # æœç´¢åˆ†äº«
    # ç¼–è¾‘å’ŒæŸ¥çœ‹æºç 
    - content.action.edit
    - content.action.view
    - content.code.copy
# ç¼–è¾‘é“¾æ¥
edit_uri: "tree/main/docs/"
extra:
  generator: false
  # ç¤¾äº¤é“¾æ¥
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YQisme
      name: githubä¸»é¡µ
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/244185393?spm_id_from=333.788.0.0
      name: bç«™ä¸»é¡µ
    - icon: fontawesome/solid/person
      link: https://eanyang7.com
      name: ä¸ªäººä¸»é¡µ

copyright: Copyright &copy; 2023 Ean Yang

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
  # - mkdocs-jupyter:
  #   include_source: True

markdown_extensions:
  - toc:
      permalink: âš“ï¸
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
